language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 9
  - 8
notifications:
  email:
    recipients:
      - $GH_EMAIL
    on_success: change
    on_failure: always
install:
  - yarn

script:
  - git config --global user.name "Travis CI"
  - git config --global user.email $GH_EMAIL
  - commitlint-travis
